### ISSUE TITLE
 Nuxt Fatal Error: Error: getaddrinfo ENOTFOUND wp.wuxt wp.wuxt:80

### ISSUE THREAD

**Issue by simplenotezy** [northosts/wuxt#116]
I am trying to run the "generate" command but I am getting below error:

![image](https://user-images.githubusercontent.com/3786627/74022263-70d63100-499d-11ea-9ef1-4abccd2b3e0e.png)

**Comment by northosts** [comment]
wp.wuxt is the container name of the WordPress-container which has to be running. The WUXT generate command has to be run from inside the WUXT-root folder not inside the nuxt folder. I cannot see from your screenshot from which location you are generating.

**Comment by simplenotezy** [comment]
I believe this is related to: https://github.com/northosts/wuxt/issues/118

**Comment by simplenotezy** [comment]
After sticking to default container names, it proceeds a bit further, but still fails with this error:

      [constantsolutions:~/Projects/wuxt]$ yarn generate                                                                                                                                               (master✱)
      yarn run v1.17.3
      $ docker exec front.wuxt yarn generate && docker-compose --log-level CRITICAL -f dist.yml up -d && docker-compose --log-level CRITICAL -f dist.yml restart && docker-compose --log-level CRITICAL down && docker-compose --log-level CRITICAL up -d
      yarn run v1.15.2
      $ nuxt generate
      ℹ Production build
      ✔ Builder initialized
      ✔ Nuxt files generated

       WARN  Browserslist: caniuse-lite is outdated. Please run next command yarn upgrade

      ℹ Compiling Client

       ERROR  (node:56) DeprecationWarning: Tapable.plugin is deprecated. Use new API on .hooks instead

      ✔ Client: Compiled with some errors in 1.29m

      Hash: 1a7c10d2c76ddfc0de84
      Version: webpack 4.39.3
      Time: 77376ms
      Built at: 02/07/2020 10:54:11 AM
                        Asset       Size  Chunks  Chunk Names
      1b2d9760ebb7cb0d9b07.js   43.6 KiB       0  app
      30b3bbb279228bca7506.js   3.91 KiB       3  pages/index
                     LICENSES  832 bytes
      d1a04dc8675325334aeb.js   59.7 KiB       5  vendors.app
      f2fdcaa899934448971e.js    164 KiB       1  commons.app
      f4ce07ad8be235bc0c34.js   1.51 KiB       2  pages/_single
      f512697fb94ac29a7b41.js   2.33 KiB       4  runtime
      Entrypoint app = f512697fb94ac29a7b41.js f2fdcaa899934448971e.js d1a04dc8675325334aeb.js 1b2d9760ebb7cb0d9b07.js

      ERROR in ./.nuxt/components/nuxt-loading.vue?vue&type=style&index=0&lang=css& (./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./node_modules/vue-loader/lib??vue-loader-options!./.nuxt/components/nuxt-loading.vue?vue&type=style&index=0&lang=css&)
      Module build failed (from ./node_modules/postcss-loader/src/index.js):
      Error: Cannot find module 'cssnano-preset-default'
          at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
          at Function.Module._load (internal/modules/cjs/loader.js:591:27)
          at Module.require (internal/modules/cjs/loader.js:723:19)
          at require (internal/modules/cjs/helpers.js:14:16)
          at resolvePreset (/var/www/app/node_modules/cssnano/dist/index.js:63:32)
          at resolveConfig (/var/www/app/node_modules/cssnano/dist/index.js:90:16)
          at /var/www/app/node_modules/cssnano/dist/index.js:115:16
          at LazyResult.run (/var/www/app/node_modules/postcss/lib/lazy-result.js:295:14)
          at LazyResult.asyncTick (/var/www/app/node_modules/postcss/lib/lazy-result.js:208:26)
          at /var/www/app/node_modules/postcss/lib/lazy-result.js:213:17
          at processTicksAndRejections (internal/process/task_queues.js:86:5)
       @ ./.nuxt/components/nuxt-loading.vue?vue&type=style&index=0&lang=css& (./node_modules/vue-style-loader??ref--3-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./node_modules/vue-loader/lib??vue-loader-options!./.nuxt/components/nuxt-loading.vue?vue&type=style&index=0&lang=css&) 4:14-327
       @ ./.nuxt/components/nuxt-loading.vue?vue&type=style&index=0&lang=css&
       @ ./.nuxt/components/nuxt-loading.vue
       @ ./.nuxt/App.js
       @ ./.nuxt/index.js
       @ ./.nuxt/client.js
       @ multi ./.nuxt/client.js

      ERROR in ./.nuxt/components/nuxt-error.vue?vue&type=style&index=0&lang=css& (./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./node_modules/vue-loader/lib??vue-loader-options!./.nuxt/components/nuxt-error.vue?vue&type=style&index=0&lang=css&)
      Module build failed (from ./node_modules/postcss-loader/src/index.js):
      Error: Cannot find module 'cssnano-preset-default'
          at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
          at Function.Module._load (internal/modules/cjs/loader.js:591:27)
          at Module.require (internal/modules/cjs/loader.js:723:19)
          at require (internal/modules/cjs/helpers.js:14:16)
          at resolvePreset (/var/www/app/node_modules/cssnano/dist/index.js:63:32)
          at resolveConfig (/var/www/app/node_modules/cssnano/dist/index.js:90:16)
          at /var/www/app/node_modules/cssnano/dist/index.js:115:16
          at LazyResult.run (/var/www/app/node_modules/postcss/lib/lazy-result.js:295:14)
          at LazyResult.asyncTick (/var/www/app/node_modules/postcss/lib/lazy-result.js:208:26)
          at /var/www/app/node_modules/postcss/lib/lazy-result.js:213:17
          at processTicksAndRejections (internal/process/task_queues.js:86:5)
       @ ./.nuxt/components/nuxt-error.vue?vue&type=style&index=0&lang=css& (./node_modules/vue-style-loader??ref--3-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./node_modules/vue-loader/lib??vue-loader-options!./.nuxt/components/nuxt-error.vue?vue&type=style&index=0&lang=css&) 4:14-325
       @ ./.nuxt/components/nuxt-error.vue?vue&type=style&index=0&lang=css&
       @ ./.nuxt/components/nuxt-error.vue
       @ ./.nuxt/index.js
       @ ./.nuxt/client.js
       @ multi ./.nuxt/client.js

      ERROR in ./pages/index.vue?vue&type=style&index=0&id=76b23ebc&lang=scss&scoped=true& (./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/vue-loader/lib??vue-loader-options!./pages/index.vue?vue&type=style&index=0&id=76b23ebc&lang=scss&scoped=true&)
      Module build failed (from ./node_modules/postcss-loader/src/index.js):
      Error: Cannot find module 'html-comment-regex'
          at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
          at Function.Module._load (internal/modules/cjs/loader.js:591:27)
          at Module.require (internal/modules/cjs/loader.js:723:19)
          at require (internal/modules/cjs/helpers.js:14:16)
          at Object.<anonymous> (/var/www/app/node_modules/is-svg/index.js:2:26)
          at Module._compile (internal/modules/cjs/loader.js:816:30)
          at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
          at Module.load (internal/modules/cjs/loader.js:685:32)
          at Function.Module._load (internal/modules/cjs/loader.js:620:12)
          at Module.require (internal/modules/cjs/loader.js:723:19)
          at require (internal/modules/cjs/helpers.js:14:16)
          at Object.<anonymous> (/var/www/app/node_modules/postcss-svgo/dist/index.js:19:14)
          at Module._compile (internal/modules/cjs/loader.js:816:30)
          at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
          at Module.load (internal/modules/cjs/loader.js:685:32)
          at Function.Module._load (internal/modules/cjs/loader.js:620:12)
       @ ./pages/index.vue?vue&type=style&index=0&id=76b23ebc&lang=scss&scoped=true& (./node_modules/vue-style-loader??ref--7-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/vue-loader/lib??vue-loader-options!./pages/index.vue?vue&type=style&index=0&id=76b23ebc&lang=scss&scoped=true&) 4:14-391
       @ ./pages/index.vue?vue&type=style&index=0&id=76b23ebc&lang=scss&scoped=true&
       @ ./pages/index.vue
       @ ./.nuxt/router.js
       @ ./.nuxt/index.js
       @ ./.nuxt/client.js
       @ multi ./.nuxt/client.js

       FATAL  Nuxt build error

        at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:5302:21)
        at processTicksAndRejections (internal/process/task_queues.js:86:5)

      tput: No value for $TERM and no -T specified

         ╭─────────────────────────────╮
         │                             │
         │   ✖ Nuxt Fatal Error        │
         │                             │
         │   Error: Nuxt build error   │
         │                             │
         ╰─────────────────────────────╯

      error Command failed with exit code 1.
